### ISSUE TITLE
[runner subcmd] init run subcommand

### ISSUE THREAD

**Issue by fuweid** [Azure/kperf#3]
- [x] Add `--clients Total number of HTTP clients` flag option

Currently, that runner uses `--conns` number as client number. By default, client-go uses HTTP2 protocol. One connection can serve multiple requests in parallel. Runner should reuse that conns to handle requests if `--clients` number is larger than `--conns`.

- [x] Add `ObserveReceivedBytes` metric method for `ResponsesStats`

For GET/LIST requests, the client-go takes long time to receive huge responses. The `TotalReceivedBytes` metric can help us to understand total traffic bytes and average RX rate during testing.

- [ ] https://github.com/Azure/kperf/issues/32
       

- [x] `Failure` in `ResponseStats` should be partitioned by HTTP verb and HTTP code
> NOTE: #15 is good enough. Ideally, we should not have a ton of errors.

- [x] Add `--result=path` flag to export result into specific file instead of stdout

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/kperf/pull/23
- [ ] https://github.com/Azure/kperf/pull/21
- [ ] https://github.com/Azure/kperf/pull/15
- [ ] https://github.com/Azure/kperf/issues/32
- [ ] https://github.com/Azure/kperf/issues/39
```
