### ISSUE TITLE
[vc subcmd] init nodepool and workload subcommands

### ISSUE THREAD

**Issue by fuweid** [Azure/kperf#4]
The `vc` sub-command is used to setup simulated cluster over real cluster and simulate pod or node's lifecycle.
This sub-command uses `kwok` to setup virtual nodes.

Ideally, the user can use existing benchmark tools, like [ArgoWorkflow](https://argoproj.github.io/argo-workflows/running-at-massive-scale/), to setup large scale objects in the cluster.

#### 1.1 kperf vc nodepool add name [options]

This command uses statefulset to setup a set of virtual nodes.

Options:

- `--nodes`: optional, INT, default: 10, the number of virtual nodes
- `--cpu`: optional, INT, default: 8, the allocatable CPU resource per node
- `--mem`: optional, INT, default: 16, the allocatable Memory resource per node (GiB)
- `--affinity`: optional, STRING SLICE, default: empty slice, format: `key=value1,value2,...`, deploy nodepool controllers into nodes with specific labels.
- `--max-pods`: optional, INT, default: 110, the max running pods per virtual node.

TODO: 
- [x] https://github.com/Azure/kperf/issues/25
- [ ] https://github.com/Azure/kperf/issues/26
- [x] https://github.com/Azure/kperf/issues/29
- [x] https://github.com/Azure/kperf/issues/30

#### 1.2 kperf vc nodepool del name

This command is to delete virtual nodepool. 

- [x] https://github.com/Azure/kperf/issues/27

#### 1.3 kperf vc nodepool list

This command is to show existing nodepool.

- [x] https://github.com/Azure/kperf/issues/28

### 2. workload 

With running virtual-nodes, users can deploy workloads with that following `nodeAffinity`.

```yaml
affinity:
   nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
            - key: type
              operator: In
              values:
                - kperf-virtualnodes
            - key: alpha.kperf.io/nodepool
              operator: In
              values:
                 - {{ nodepool name }}
```

The `workload` command is a collection of common workloads to mutate kubernetes cluster. 

TODO:
- [ ] https://github.com/Azure/kperf/issues/31

> NOTE: We can introduce Argo-Workflow/Kyverno/... workloads into `vc/workload`. But for this issue, we just need one subcommand. 

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/kperf/pull/7
- [ ] https://github.com/Azure/kperf/pull/17
- [ ] https://github.com/Azure/kperf/issues/25
- [ ] https://github.com/Azure/kperf/issues/26
- [ ] https://github.com/Azure/kperf/issues/27
- [ ] https://github.com/Azure/kperf/issues/28
- [ ] https://github.com/Azure/kperf/issues/29
- [ ] https://github.com/Azure/kperf/issues/30
- [ ] https://github.com/Azure/kperf/issues/31
```
