### ISSUE TITLE
[runnergroup subcmd] initialize run/wait/status/result/del subcommands 

### ISSUE THREAD

**Issue by fuweid** [Azure/kperf#5]
## Background

The `runner` is short-live command. Runner's result should be uploaded to long-running server which can gather data and make aggregate summary. And user can query runner's status from long-running server. For multi-runner, the long-running server is used as temporary result storage so that we don't need to introduce extra storage.

## Tasks

- [x] https://github.com/Azure/kperf/issues/33
- [x] https://github.com/Azure/kperf/issues/34
- [x] https://github.com/Azure/kperf/issues/35
- [x] https://github.com/Azure/kperf/issues/36
- [x] https://github.com/Azure/kperf/issues/37
- [x] https://github.com/Azure/kperf/issues/38
